[context.production]
  command = "pnpm run build && echo \"PUBLIC_DEPLOY_URL=$URL\" > dist/.env.local"

[context.deploy-preview]
  command = "pnpm run build && echo \"PUBLIC_DEPLOY_URL=$DEPLOY_PRIME_URL\" > dist/.env.local"